# BTC Quant Configuration
# This file contains all configurable parameters for the trading system

# Data Configuration
data:
  default_ticker: "BTC-USD"
  default_start_date: null  # Auto-calculated for 3 years
  default_end_date: null    # Auto-calculated (today)
  data_source: "yfinance"
  default_interval: "1d"    # Primary timeframe for analysis
  timeframes: ["1h", "4h", "1d", "1w"]  # Multi-timeframe support
  min_years: 1              # Minimum years of data required
  preferred_years: 3        # Preferred years of data
  market_hours: [9, 17]     # Market hours filter
  min_data_points: 100
  
  # Data quality thresholds
  quality_thresholds:
    min_quality_score: 0.95
    max_missing_values: 0.05
    max_data_gaps: 0.10
    
  # Timeframe-specific settings
  timeframe_settings:
    "1h":
      min_data_points: 8760  # 1 year of hourly data
      resample_freq: "H"
      gap_fill_method: "forward_fill"
    "4h":
      min_data_points: 2190  # 1 year of 4-hour data
      resample_freq: "4H"
      gap_fill_method: "forward_fill"
    "1d":
      min_data_points: 365   # 1 year of daily data
      resample_freq: "D"
      gap_fill_method: "forward_fill"
    "1w":
      min_data_points: 52    # 1 year of weekly data
      resample_freq: "W"
      gap_fill_method: "forward_fill"

# Model Configuration
model:
  algorithm: "XGBoost"
  random_state: 42
  eval_metric: "logloss"
  default_n_splits: 5
  target_lookahead: 1

# Feature Engineering
features:
  # Basic technical indicators
  technical_indicators:
    - "SMA"
    - "EMA"
    - "RSI"
    - "MACD"
    - "Bollinger_Bands"
    - "Stochastic"
    - "Williams_R"
    - "ATR"
    - "OBV"
    - "VWAP"
  
  # Advanced microstructure features
  microstructure_features:
    - "VWAP_Enhanced"
    - "Order_Flow_Imbalance"
    - "Bid_Ask_Spread"
    - "Volume_Microstructure"
    - "Price_Microstructure"
  
  # Time-based features
  time_features:
    - "Hour_Encoding"
    - "Day_Encoding"
    - "Market_Hours"
    - "Cyclical_Encoding"
  
  # Fractional differentiation
  fractional_features:
    enabled: true
    d_values: [0.3, 0.5, 0.7]
    series: ["Price", "Volume", "Returns"]
  
  # Rolling window periods
  rolling_windows: [5, 10, 20, 50]
  
  # Price-based features
  price_features:
    - "returns"
    - "log_returns"
    - "price_ratios"
    - "lagged_features"
    - "fractional_differentiation"

# Evaluation Metrics
evaluation:
  risk_free_rate: 0.02
  required_metrics:
    - "sharpe_ratio"
    - "max_drawdown"
    - "volatility"
    - "win_rate"
    - "profit_factor"
    - "auc"

# Trading Strategy
strategy:
  default_signal_threshold: 0.5
  position_sizing: "equal_weight"
  risk_management:
    stop_loss: null
    take_profit: null
    max_position_size: null

# Transaction Costs & Market Friction
transaction_costs:
  # Fee structure (percentage of trade value)
  maker_fee: 0.0004  # 0.04% for maker orders
  taker_fee: 0.0006  # 0.06% for taker orders
  default_fee: 0.0006  # Default to taker fee
  
  # Slippage model parameters
  slippage:
    base_slippage: 0.0001  # 0.01% base slippage
    volatility_multiplier: 0.5  # Multiplier for ATR-based slippage
    volume_impact: 0.00005  # Impact per $100k traded
    max_slippage: 0.005  # Maximum 0.5% slippage
    
  # Position sizing parameters
  position_sizing:
    default_risk_per_trade: 0.02  # 2% risk per trade
    max_position_size: 0.10  # Maximum 10% of portfolio
    volatility_target: 0.15  # Target 15% annual volatility

# Performance Thresholds
thresholds:
  minimum_accuracy: 0.50
  minimum_sharpe: 0.30
  maximum_drawdown: 0.20
  minimum_auc: 0.55 