version: '3.8'

services:
  btc-quant:
    build: .
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: python enhanced_main.py
    
  jupyter:
    build: .
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./results:/app/results
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    depends_on:
      - btc-quant 