version: '3.8'

services:
  btc-quant:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: echo "BTC Quant project initialized successfully" 