name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.11-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.11-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
      timeout-minutes: 5
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # Install core dependencies first
        pip install --no-cache-dir --timeout 600 numpy pandas matplotlib
        # Install remaining dependencies
        pip install --no-cache-dir --timeout 600 -r requirements.txt
        pip install --no-cache-dir --timeout 600 -r requirements-dev.txt
      timeout-minutes: 15
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=88 --extend-ignore=E203,W503
        # exit-zero treats all errors as warnings
        flake8 src/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics --extend-ignore=E203,W503
      timeout-minutes: 5
    
    - name: Format check with black
      run: |
        black --check --line-length=88 src/ tests/
      timeout-minutes: 5
    
    - name: Test with pytest
      run: |
        pytest tests/ -v --cov=src --cov-report=xml
      timeout-minutes: 10
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false 